version: "2"
services:
  frontend:
    image: bde2020/ember-stack-builder-frontend:0.2.0
    ports:
      - "88:80"
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.2.0
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:1.1.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.1.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  backend:
    image: bde2020/mu-docker-compose-file-service:0.1.0
    links:
      - db:database
  migrationsservice:
      image: semtech/mu-migrations-service
      links:
        - db:database
      volumes:
        - ./config/migrations:/data/migrations
